export const text = {
  English: {
    navHome: "Home",
    navLT: "LighTide",
    navResults: "Results",
    attributionText: "Attribution:",
    attributionWarning: "Nature is unpredictable.",
    attributionReminder: "Use the information presented at your own risk.",
    attributionLink: "Created Oct 2021 by ZY of GA SEI-32. Github code",
    attributionLinkSpan: " here.",
    homeWelcome: "Welcome to LighTide Maps!",
    homeIntro:
      "Get sunrise / sunset & tide details based on the location and date.",
    home1:
      "1. Search a place / Select a point on the map to pinpoint a location.",
    home2: "2. Choose a date. By default, the date is set to today.",
    home3: `3. Select "Get details!" to retrieve the information.`,
    homeNote: "Note that tide requests are capped at 50 per day.",
    homeButton: "Let's Go!",
  },
  简体中文: {
    navHome: "主页",
    navLT: "潮汐",
    navResults: "结果",
    attributionText: "归属:",
    attributionWarning: "大自然是不可预测的。",
    attributionReminder: "请自行承担使用所提供的信息的风险。",
    attributionLink: "由ZY（GA SEI-32）于2021年10月创建。Github代码",
    attributionLinkSpan: " 在这里。",
    homeWelcome: "欢迎来到LighTide 地图！",
    homeIntro: "根据位置和日期获取日出/日落和潮汐详情。",
    home1: "1. 搜索地点/在地图上选择一个点以确定位置。",
    home2: "2. 选择日期。默认情况下，日期设置为今天。",
    home3: `3. 选择“获取详情！”以检索信息。`,
    homeNote: "请注意，潮汐请求每天限制为50个。",
    homeButton: "走吧！",
  },
  繁体中文: {
    navHome: "主頁",
    navLT: "潮汐",
    navResults: "結果",
    attributionText: "歸屬:",
    attributionWarning: "大自然是不可預測的。",
    attributionReminder: "請自行承擔使用所提供的信息的風險。",
    attributionLink: "由ZY（GA SEI-32）於2021年10月創建。Github代碼",
    attributionLinkSpan: " 在這裡。",
    homeWelcome: "歡迎來到LighTide 地圖！",
    homeIntro: "根據位置和日期獲取日出/日落和潮汐詳情。",
    home1: "1. 搜索地點/在地圖上選擇一個點以確定位置。",
    home2: "2. 選擇日期。默認情況下，日期設置為今天。",
    home3: `3. 選擇“獲取詳情！”以檢索信息。`,
    homeNote: "請注意，潮汐請求每天限制為50個。",
    homeButton: "走吧！",
  },
};
