export const text = {
  English: {
    navHome: "Home",
    navLT: "LighTide",
    navResults: "Results",
    attributionText: "Attribution:",
    attributionWarning: "Nature is unpredictable.",
    attributionReminder: "Use the information presented at your own risk.",
    attributionLink: "Created Oct 2021 by ZY of GA SEI-32. Github code",
    attributionLinkSpan: " here.",
  },
  简体中文: {
    navHome: "主页",
    navLT: "潮汐",
    navResults: "结果",
    attributionText: "归属:",
    attributionWarning: "大自然是不可预测的。",
    attributionReminder: "请自行承担使用所提供的信息的风险。",
    attributionLink: "由ZY（GA SEI-32）于2021年10月创建。Github代码",
    attributionLinkSpan: " 在这里。",
  },
  繁体中文: {
    navHome: "主頁",
    navLT: "潮汐",
    navResults: "結果",
    attributionText: "歸屬:",
    attributionWarning: "大自然是不可預測的。",
    attributionReminder: "請自行承擔使用所提供的信息的風險。",
    attributionLink: "由ZY（GA SEI-32）於2021年10月創建。Github代碼",
    attributionLinkSpan: " 在這裡。",
  },
};
