export const text = {
  English: {
    navHome: "Home",
    navLT: "LighTide",
    navResults: "Results",
    attributionText: "Attribution:",
    attributionWarning: "Nature is unpredictable.",
    attributionReminder: "Use the information presented at your own risk.",
    attributionLink: "Created Oct 2021 by ZY of GA SEI-32. Github code",
    attributionLinkSpan: " here.",
    homeWelcome: "Welcome to LighTide Maps!",
    homeIntro:
      "Get sunrise / sunset & tide details based on the location and date.",
    home1:
      "1. Search a place / Select a point on the map to pinpoint a location.",
    home2: "2. Choose a date. By default, the date is set to today.",
    home3: `3. Select "Get details!" to retrieve the information.`,
    homeNote: "Note that tide requests are capped at 50 per day.",
    homeButton: "Let's Go!",
    searchDetailsDate: "Date:",
    searchDetailsLocation: "Locate a place:",
    searchPlaceholder: "Address / Place name",
    searchDetailsButton: "Search",
    mapsPopup: "Selected point",
    mapsLatitude: "Latitude",
    mapsLongitude: "Longitude",
    mapsStation: "station",
    appGetDetails: "Get Details",
    sunInfo: "Sunrise & Sunset Times",
    sunSunrise: "Sunrise",
    sunSunset: "Sunset",
    sunSolarNoon: "Solar noon",
    sunDayLength: "Day length",
    sunCivilTwilightBegin: "Civil twilight begin",
    sunCivilTwilightEnd: "Civil twilight end",
    sunNauticalTwilightBegin: "Nautical twilight begin",
    sunNauticalTwilightEnd: "Nautical twilight end",
    sunAstronomicalTwilightBegin: "Astronomical twilight begin",
    sunAstronomicalTwilightEnd: "Astronomical twilight end",
    sunHours: "hours",
    sunMinutes: "minutes",
    sunSeconds: "seconds",
    tideISO: "ISO Date/Time",
    tideLocal: "Local Date/Time",
    tideType: "Tide Type",
    tideHeight: "Height",
    tideMetres: "metres",
    tideTitle: "Tides",
    tideRequestCount: "Request count",
    tideDailyLimit: "Daily limit",
    tideStationName: "Station name",
    tideDistanceStation: "Distance between station and requested coordinate",
    tideKilometres: "kilometres",
    tideStationCoordinates: "Station coordinates",
    tideLimitReached1: "Sorry, tide request limit reached for today!",
    tideLimitReached2: "Please try again tomorrow",
    tideHigh: "High",
    tideLow: "Low",
    chartTitle: "Tide Chart",
    chartTimeSeries: "Time Series",
    chartLimitReached1:
      "Tide request limit reached for today, so no chart generated!",
  },
  简体中文: {
    navHome: "主页",
    navLT: "潮汐",
    navResults: "结果",
    attributionText: "归属:",
    attributionWarning: "大自然是不可预测的。",
    attributionReminder: "请自行承担使用所提供的信息的风险。",
    attributionLink: "由ZY（GA SEI-32）于2021年10月创建。Github代码",
    attributionLinkSpan: " 在这里。",
    homeWelcome: "欢迎来到LighTide 地图！",
    homeIntro: "根据位置和日期获取日出/日落和潮汐详情。",
    home1: "1. 搜索地点/在地图上选择一个点以确定位置。",
    home2: "2. 选择日期。默认情况下，日期设置为今天。",
    home3: `3. 选择“获取详情！”以检索信息。`,
    homeNote: "请注意，潮汐请求每天限制为50个。",
    homeButton: "走吧！",
    searchDetailsDate: "日期:",
    searchDetailsLocation: "搜索地点:",
    searchPlaceholder: "地址/地名",
    searchDetailsButton: "搜索",
    mapsPopup: "选定点",
    mapsLatitude: "纬度",
    mapsLongitude: "经度",
    mapsStation: "站",
    appGetDetails: "获取详情",
    sunInfo: "日出和日落时间",
    sunSunrise: "日出",
    sunSunset: "日落",
    sunSolarNoon: "太阳正午",
    sunDayLength: "白天长度",
    sunCivilTwilightBegin: "民用黄昏开始",
    sunCivilTwilightEnd: "民用黄昏结束",
    sunNauticalTwilightBegin: "航海黄昏开始",
    sunNauticalTwilightEnd: "航海黄昏结束",
    sunAstronomicalTwilightBegin: "天文黄昏开始",
    sunAstronomicalTwilightEnd: "天文黄昏结束",
    sunHours: "小时",
    sunMinutes: "分钟",
    sunSeconds: "秒",
    tideISO: "ISO 日期/时间",
    tideLocal: "本地日期/时间",
    tideType: "潮汐类型",
    tideHeight: "高度",
    tideMetres: "米",
    tideTitle: "潮汐",
    tideRequestCount: "请求次数",
    tideDailyLimit: "每日限额",
    tideStationName: "站名",
    tideDistanceStation: "站点与请求坐标之间的距离",
    tideKilometres: "公里",
    tideStationCoordinates: "站点坐标",
    tideLimitReached1: "抱歉，今天潮汐请求限制已达到！",
    tideLimitReached2: "请明天再试",
    tideHigh: "高",
    tideLow: "低",
    chartTitle: "潮汐图",
    chartTimeSeries: "时间序列",
    chartLimitReached1: "潮汐请求限制已达到，因此未生成图表！",
  },
  繁体中文: {
    navHome: "主頁",
    navLT: "潮汐",
    navResults: "結果",
    attributionText: "歸屬:",
    attributionWarning: "大自然是不可預測的。",
    attributionReminder: "請自行承擔使用所提供的信息的風險。",
    attributionLink: "由ZY（GA SEI-32）於2021年10月創建。Github代碼",
    attributionLinkSpan: " 在這裡。",
    homeWelcome: "歡迎來到LighTide 地圖！",
    homeIntro: "根據位置和日期獲取日出/日落和潮汐詳情。",
    home1: "1. 搜索地點/在地圖上選擇一個點以確定位置。",
    home2: "2. 選擇日期。默認情況下，日期設置為今天。",
    home3: `3. 選擇“獲取詳情！”以檢索信息。`,
    homeNote: "請注意，潮汐請求每天限制為50個。",
    homeButton: "走吧！",
    searchDetailsDate: "日期:",
    searchDetailsLocation: "搜索地點:",
    searchPlaceholder: "地址/地名",
    searchDetailsButton: "搜索",
    mapsPopup: "選定點",
    mapsLatitude: "緯度",
    mapsLongitude: "經度",
    mapsStation: "站",
    appGetDetails: "獲取詳情",
    sunInfo: "日出和日落時間",
    sunSunrise: "日出",
    sunSunset: "日落",
    sunSolarNoon: "太陽正午",
    sunDayLength: "白天長度",
    sunCivilTwilightBegin: "民用黃昏開始",
    sunCivilTwilightEnd: "民用黃昏結束",
    sunNauticalTwilightBegin: "航海黃昏開始",
    sunNauticalTwilightEnd: "航海黃昏結束",
    sunAstronomicalTwilightBegin: "天文黃昏開始",
    sunAstronomicalTwilightEnd: "天文黃昏結束",
    sunHours: "小時",
    sunMinutes: "分鐘",
    sunSeconds: "秒",
    tideISO: "ISO 日期/時間",
    tideLocal: "本地日期/時間",
    tideType: "潮汐類型",
    tideHeight: "高度",
    tideMetres: "米",
    tideTitle: "潮汐",
    tideRequestCount: "請求次數",
    tideDailyLimit: "每日限額",
    tideStationName: "站名",
    tideDistanceStation: "站點與請求坐標之間的距離",
    tideKilometres: "公里",
    tideStationCoordinates: "站點坐標",
    tideLimitReached1: "抱歉，今天潮汐請求限制已達到！",
    tideLimitReached2: "請明天再試",
    tideHigh: "高",
    tideLow: "低",
    chartTitle: "潮汐圖",
    chartTimeSeries: "時間序列",
    chartLimitReached1: "潮汐請求限制已達到，因此未生成圖表！",
  },
};
